In [1]:
import pandas as pd

In [2]:
df =pd.read_csv(r'C:\Users\chand\OneDrive\Desktop\Data science\data-science-ai-and-ml\projects\credit\Credit (1).csv')

In [3]:
df.dropna(inplace=True)

In [4]:
df

age            job  marital  ... duration  campaign approval
0     30.0     unemployed  married  ...     79.0         1       no
1     33.0       services  married  ...    220.0         1       no
2     35.0     management   single  ...    185.0         1       no
3     30.0     management  married  ...    199.0         4       no
4     59.0    blue-collar  married  ...    226.0         1       no
...    ...            ...      ...  ...      ...       ...      ...
4516  99.0       services  married  ...    329.0         5       no
4517  57.0  self-employed  married  ...   -153.0         1       no
4518  57.0     technician  married  ...    151.0        11       no
4519  28.0    blue-collar  married  ...    129.0         4       no
4520  44.0   entrepreneur   single  ...    345.0         2       no

[4501 rows x 9 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4501 entries, 0 to 4520
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   age        4501 non-null   float64
 1   job        4501 non-null   object 
 2   marital    4501 non-null   object 
 3   education  4501 non-null   object 
 4   balance    4501 non-null   int64  
 5   housing    4501 non-null   object 
 6   duration   4501 non-null   float64
 7   campaign   4501 non-null   int64  
 8   approval   4501 non-null   object 
dtypes: float64(2), int64(2), object(5)
memory usage: 351.6+ KB


In [6]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...  
4516    False
4517    False
4518    False
4519    False
4520    False
Length: 4501, dtype: bool

In [7]:
df.duplicated().sum()

np.int64(1)

In [8]:
df.drop_duplicates(inplace=True)

In [9]:
df.describe()

age       balance      duration     campaign
count  4500.000000   4500.000000  4.500000e+03  4500.000000
mean     41.391111   1423.561111  6.007646e+03     2.792667
std      13.983651   3014.058886  3.578213e+05     3.108241
min     -38.000000  -3313.000000 -7.990000e+02     1.000000
25%      33.000000     68.750000  1.040000e+02     1.000000
50%      39.000000    444.500000  1.850000e+02     2.000000
75%      49.000000   1480.000000  3.290000e+02     3.000000
max     416.000000  71188.000000  2.395650e+07    50.000000

In [10]:
df

age            job  marital  ... duration  campaign approval
0     30.0     unemployed  married  ...     79.0         1       no
1     33.0       services  married  ...    220.0         1       no
2     35.0     management   single  ...    185.0         1       no
3     30.0     management  married  ...    199.0         4       no
4     59.0    blue-collar  married  ...    226.0         1       no
...    ...            ...      ...  ...      ...       ...      ...
4516  99.0       services  married  ...    329.0         5       no
4517  57.0  self-employed  married  ...   -153.0         1       no
4518  57.0     technician  married  ...    151.0        11       no
4519  28.0    blue-collar  married  ...    129.0         4       no
4520  44.0   entrepreneur   single  ...    345.0         2       no

[4500 rows x 9 columns]

In [11]:
df.head(10)

age            job  marital  education  ...  housing duration  campaign  approval
0  30.0     unemployed  married    primary  ...       no     79.0         1        no
1  33.0       services  married  secondary  ...      yes    220.0         1        no
2  35.0     management   single   tertiary  ...      yes    185.0         1        no
3  30.0     management  married   tertiary  ...      yes    199.0         4        no
4  59.0    blue-collar  married  secondary  ...      yes    226.0         1        no
5  35.0     management   single   tertiary  ...       no    141.0         2        no
6  36.0  self-employed  married   tertiary  ...      yes    341.0         1        no
7  39.0     technician  married  secondary  ...      yes    151.0         2        no
8  41.0   entrepreneur  married   tertiary  ...      yes     57.0         2        no
9  43.0       services  married    primary  ...      yes    313.0         1        no

[10 rows x 9 columns]

In [12]:
df.tail(10)

age            job  marital  ... duration  campaign approval
4511  46.0    blue-collar  married  ...   1263.0         2      yes
4512  40.0    blue-collar  married  ...    660.0         2       no
4513  49.0    blue-collar  married  ...    356.0         2       no
4514  38.0    blue-collar  married  ...     45.0         4       no
4515  32.0       services   single  ...    624.0         5       no
4516  99.0       services  married  ...    329.0         5       no
4517  57.0  self-employed  married  ...   -153.0         1       no
4518  57.0     technician  married  ...    151.0        11       no
4519  28.0    blue-collar  married  ...    129.0         4       no
4520  44.0   entrepreneur   single  ...    345.0         2       no

[10 rows x 9 columns]

In [13]:
df['job'].value_counts()

job
management       958
blue-collar      943
technician       765
admin.           477
services         415
retired          230
self-employed    182
entrepreneur     168
unemployed       128
housemaid        112
student           84
unknown           38
Name: count, dtype: int64

In [14]:
df['job'].unique()

array(['unemployed', 'services', 'management', 'blue-collar',
       'self-employed', 'technician', 'entrepreneur', 'admin.', 'student',
       'housemaid', 'retired', 'unknown'], dtype=object)

In [15]:
df['job'].nunique()

12

In [16]:
df[df['job'] == 'blue-collar']

age          job  marital  ... duration  campaign approval
4     59.0  blue-collar  married  ...    226.0         1       no
14    31.0  blue-collar  married  ...     89.0         1       no
26    55.0  blue-collar  married  ...    247.0         1       no
37    32.0  blue-collar  married  ...    132.0         1      yes
42    52.0  blue-collar  married  ...    365.0         1       no
...    ...          ...      ...  ...      ...       ...      ...
4511  46.0  blue-collar  married  ...   1263.0         2      yes
4512  40.0  blue-collar  married  ...    660.0         2       no
4513  49.0  blue-collar  married  ...    356.0         2       no
4514  38.0  blue-collar  married  ...     45.0         4       no
4519  28.0  blue-collar  married  ...    129.0         4       no

[943 rows x 9 columns]

In [17]:
df.rename(columns = {'job':'job status'}, inplace=True)

In [18]:
df

age     job status  marital  ... duration  campaign approval
0     30.0     unemployed  married  ...     79.0         1       no
1     33.0       services  married  ...    220.0         1       no
2     35.0     management   single  ...    185.0         1       no
3     30.0     management  married  ...    199.0         4       no
4     59.0    blue-collar  married  ...    226.0         1       no
...    ...            ...      ...  ...      ...       ...      ...
4516  99.0       services  married  ...    329.0         5       no
4517  57.0  self-employed  married  ...   -153.0         1       no
4518  57.0     technician  married  ...    151.0        11       no
4519  28.0    blue-collar  married  ...    129.0         4       no
4520  44.0   entrepreneur   single  ...    345.0         2       no

[4500 rows x 9 columns]

In [19]:
df.drop(['campaign'] ,axis=1 ,inplace=True)

In [20]:
df

age     job status  marital  ... housing  duration approval
0     30.0     unemployed  married  ...      no      79.0       no
1     33.0       services  married  ...     yes     220.0       no
2     35.0     management   single  ...     yes     185.0       no
3     30.0     management  married  ...     yes     199.0       no
4     59.0    blue-collar  married  ...     yes     226.0       no
...    ...            ...      ...  ...     ...       ...      ...
4516  99.0       services  married  ...     yes     329.0       no
4517  57.0  self-employed  married  ...     yes    -153.0       no
4518  57.0     technician  married  ...      no     151.0       no
4519  28.0    blue-collar  married  ...      no     129.0       no
4520  44.0   entrepreneur   single  ...     yes     345.0       no

[4500 rows x 8 columns]

In [21]:
char = df.select_dtypes(include='object')

In [22]:
char

job status  marital  education housing approval
0        unemployed  married    primary      no       no
1          services  married  secondary     yes       no
2        management   single   tertiary     yes       no
3        management  married   tertiary     yes       no
4       blue-collar  married  secondary     yes       no
...             ...      ...        ...     ...      ...
4516       services  married  secondary     yes       no
4517  self-employed  married   tertiary     yes       no
4518     technician  married  secondary      no       no
4519    blue-collar  married  secondary      no       no
4520   entrepreneur   single   tertiary     yes       no

[4500 rows x 5 columns]

In [23]:
num=df.select_dtypes(exclude='object')

In [24]:
num

age  balance  duration
0     30.0     1787      79.0
1     33.0     4789     220.0
2     35.0     1350     185.0
3     30.0     1476     199.0
4     59.0        0     226.0
...    ...      ...       ...
4516  99.0     -333     329.0
4517  57.0    -3313    -153.0
4518  57.0      295     151.0
4519  28.0     1137     129.0
4520  44.0     1136     345.0

[4500 rows x 3 columns]

In [25]:
char['marital'].unique()

array(['married', 'single', 'divorced'], dtype=object)

In [26]:
job_status_dic = {
    'married': 0,
    'single':1,
    'divorced': 2
}

In [27]:
char['marital'] = char['marital'].map(job_status_dic)

In [28]:
char['marital'].unique()

array([0, 1, 2])

In [29]:
char['education'].unique()

array(['primary', 'secondary', 'tertiary', 'unknown'], dtype=object)

In [30]:
education_dict = {
    'primary': 0,
    'secondary': 1,
    'tertiary':2,
    'unknown':3
}

In [31]:
char['education'] = char['education'].map(education_dict)

In [32]:
char['education'].unique()

array([0, 1, 2, 3])

In [33]:
from sklearn.preprocessing import LabelEncoder
Le =LabelEncoder()

char['job status'] =Le.fit_transform(df['job status'])
#df['balance'] =le.fit_transform(df['balance'])
char['housing'] =Le.fit_transform(df['housing'])

In [34]:
char['job status'].unique()

array([10,  7,  4,  1,  6,  9,  2,  0,  8,  3,  5, 11])

In [35]:
num

age  balance  duration
0     30.0     1787      79.0
1     33.0     4789     220.0
2     35.0     1350     185.0
3     30.0     1476     199.0
4     59.0        0     226.0
...    ...      ...       ...
4516  99.0     -333     329.0
4517  57.0    -3313    -153.0
4518  57.0      295     151.0
4519  28.0     1137     129.0
4520  44.0     1136     345.0

[4500 rows x 3 columns]

In [36]:
char

job status  marital  education  housing approval
0             10        0          0        0       no
1              7        0          1        1       no
2              4        1          2        1       no
3              4        0          2        1       no
4              1        0          1        1       no
...          ...      ...        ...      ...      ...
4516           7        0          1        1       no
4517           6        0          2        1       no
4518           9        0          1        0       no
4519           1        0          1        0       no
4520           2        1          2        1       no

[4500 rows x 5 columns]

In [37]:
clean_data =pd.concat([char,num],axis =1)

In [38]:
app_dict = {'no':0,'yes':1}

In [39]:
clean_data['approval']= clean_data['approval'].map(app_dict)

In [40]:
clean_data

job status  marital  education  ...   age  balance  duration
0             10        0          0  ...  30.0     1787      79.0
1              7        0          1  ...  33.0     4789     220.0
2              4        1          2  ...  35.0     1350     185.0
3              4        0          2  ...  30.0     1476     199.0
4              1        0          1  ...  59.0        0     226.0
...          ...      ...        ...  ...   ...      ...       ...
4516           7        0          1  ...  99.0     -333     329.0
4517           6        0          2  ...  57.0    -3313    -153.0
4518           9        0          1  ...  57.0      295     151.0
4519           1        0          1  ...  28.0     1137     129.0
4520           2        1          2  ...  44.0     1136     345.0

[4500 rows x 8 columns]

In [41]:
clean_data.to_csv('cr.csv')

In [42]:
clean_data

job status  marital  education  ...   age  balance  duration
0             10        0          0  ...  30.0     1787      79.0
1              7        0          1  ...  33.0     4789     220.0
2              4        1          2  ...  35.0     1350     185.0
3              4        0          2  ...  30.0     1476     199.0
4              1        0          1  ...  59.0        0     226.0
...          ...      ...        ...  ...   ...      ...       ...
4516           7        0          1  ...  99.0     -333     329.0
4517           6        0          2  ...  57.0    -3313    -153.0
4518           9        0          1  ...  57.0      295     151.0
4519           1        0          1  ...  28.0     1137     129.0
4520           2        1          2  ...  44.0     1136     345.0

[4500 rows x 8 columns]

In [43]:
x = clean_data.drop('approval', axis= 1)

In [44]:
y = clean_data[['approval']]

In [45]:
x

job status  marital  education  housing   age  balance  duration
0             10        0          0        0  30.0     1787      79.0
1              7        0          1        1  33.0     4789     220.0
2              4        1          2        1  35.0     1350     185.0
3              4        0          2        1  30.0     1476     199.0
4              1        0          1        1  59.0        0     226.0
...          ...      ...        ...      ...   ...      ...       ...
4516           7        0          1        1  99.0     -333     329.0
4517           6        0          2        1  57.0    -3313    -153.0
4518           9        0          1        0  57.0      295     151.0
4519           1        0          1        0  28.0     1137     129.0
4520           2        1          2        1  44.0     1136     345.0

[4500 rows x 7 columns]

In [46]:
y

approval
0            0
1            0
2            0
3            0
4            0
...        ...
4516         0
4517         0
4518         0
4519         0
4520         0

[4500 rows x 1 columns]

In [47]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)


In [48]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((3600, 7), (900, 7), (3600, 1), (900, 1))

In [49]:

from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train, y_train)

LinearRegression()

In [50]:
lr.score(x_train, y_train)

0.01621723827922139

In [51]:
lr.score(x_test, y_test)

-0.12005842724372906

In [52]:
pred = lr.predict(x_test)

In [53]:
pred

array([[0.07185557],
       [0.07146789],
       [0.25933384],
       [0.15378537],
       [0.14352137],
       [0.07217195],
       [0.16749961],
       [0.1956114 ],
       [0.13587295],
       [0.07445966],
       [0.12361016],
       [0.06312318],
       [0.13515818],
       [0.06302581],
       [0.06018344],
       [0.17561028],
       [0.07771442],
       [0.14489016],
       [0.14204027],
       [0.14203589],
       [0.19030719],
       [0.10198027],
       [0.14186145],
       [0.12780753],
       [0.10271148],
       [0.09725515],
       [0.19981905],
       [0.10379738],
       [0.1300717 ],
       [0.10580677],
       [0.1583588 ],
       [0.07105861],
       [0.06894857],
       [0.13941443],
       [0.07241718],
       [0.07636343],
       [0.19981999],
       [0.15266002],
       [0.14240226],
       [0.07406136],
       [0.13305634],
       [0.1525255 ],
       [0.08178764],
       [0.16647508],
       [0.18866269],
       [0.0747238 ],
       [0.06611194],
       [0.092

In [54]:
import joblib
joblib.dump(lr, 'model.lb')

['model.lb']

In [55]:
joblib.dump

<function joblib.numpy_pickle.dump(value, filename, compress=0, protocol=None)>

In [56]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)


In [57]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((3600, 7), (900, 7), (3600, 1), (900, 1))

In [58]:
from sklearn.svm import SVR
svr =SVR()
svr.fit(x_train, y_train)

C:\Users\chand\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [59]:
svr.score(x_train, y_train)

-0.00048523026127522684

In [60]:
svr.score(x_test, y_test)

-0.017887842905912832

In [61]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)


In [62]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((3600, 7), (900, 7), (3600, 1), (900, 1))

In [63]:
from sklearn.svm import SVC
svc = SVC()
svc.fit(x_train, y_train)

C:\Users\chand\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC()

In [64]:
svc.score(x_test, y_test)

0.8722222222222222

In [65]:
from sklearn.datasets import load_iris
x,y = load_iris(return_X_y=True)
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [66]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [67]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [68]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)


In [69]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(x_train, y_train)

KNeighborsClassifier()

In [70]:
knn.get_params()

{'algorithm': 'auto',
 'leaf_size': 30,
 'metric': 'minkowski',
 'metric_params': None,
 'n_jobs': None,
 'n_neighbors': 5,
 'p': 2,
 'weights': 'uniform'}

In [71]:
knn.score(x_train,y_train)

0.9583333333333334

In [72]:
knn.predict(x_test)

array([1, 0, 2, 2, 1, 2, 1, 1, 2, 0, 1, 0, 2, 2, 0, 2, 0, 1, 0, 0, 0, 1,
       0, 2, 2, 1, 2, 2, 0, 2])

In [73]:
import pandas as pd
from sklearn.metrics import classification_report
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split


In [74]:
df =pd.read_csv('cr.csv')

In [75]:
x = df.drop('balance', axis = 1)
y = df[['balance']]

In [76]:
x

Unnamed: 0  job status  marital  ...  approval   age  duration
0              0          10        0  ...         0  30.0      79.0
1              1           7        0  ...         0  33.0     220.0
2              2           4        1  ...         0  35.0     185.0
3              3           4        0  ...         0  30.0     199.0
4              4           1        0  ...         0  59.0     226.0
...          ...         ...      ...  ...       ...   ...       ...
4495        4516           7        0  ...         0  99.0     329.0
4496        4517           6        0  ...         0  57.0    -153.0
4497        4518           9        0  ...         0  57.0     151.0
4498        4519           1        0  ...         0  28.0     129.0
4499        4520           2        1  ...         0  44.0     345.0

[4500 rows x 8 columns]

In [77]:
y

balance
0        1787
1        4789
2        1350
3        1476
4           0
...       ...
4495     -333
4496    -3313
4497      295
4498     1137
4499     1136

[4500 rows x 1 columns]

In [78]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=42)

In [79]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(x_train,y_train)

C:\Users\chand\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\multiclass.py:213: UserWarning: The number of unique classes is greater than 50% of the number of samples.
  y_type = type_of_target(y, input_name="y")


DecisionTreeClassifier()

In [80]:
df =DecisionTreeClassifier()
df.fit(x_train, y_train)

C:\Users\chand\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\multiclass.py:213: UserWarning: The number of unique classes is greater than 50% of the number of samples.
  y_type = type_of_target(y, input_name="y")


DecisionTreeClassifier()

In [81]:
pred = df.predict(x_test)

In [82]:
pred

array([ 4148,  5306,  6563,  3726,  9676,   295,  1026,     0,   306,
         858,   340,     0,   781,  8652,   687,  2087,  -839,  7020,
           0,   286,   136,   201,     0,  2581,   481,   183,  1784,
         744,     0,  1466,   679,   186,   289,    46,   471,    88,
           0,   230,    51,   574,  -386,  2923,    10,    34,   414,
        4148,   101,    35,  4020,   868, 21664,  1830,   -15,    23,
         398,  2349,   769,   214,   383,   816,    35,  5902,   694,
        2581,    81,    18,   186,   310,  5306,   606,  1040,  1351,
        1831,   153,  1071,   117,   251,    93,   153,    75,     0,
         142,   -72,   192,  2523,  7708,   414,   495,    62,  2581,
        8304,  1587,   750,   407,   -41,   865,   768,  1076,  5543,
          71,   625,   796,     5,   671,   856,  1893,  -226,  5092,
          -2, 12223,    79,   585,   430,     0,   255,  1568,   -37,
         194,   607,  2959,  3872,  1172,  -200,  1091,     0,  5057,
        1582,  -276,

In [83]:
pred = df.predict(x_test)

In [84]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

       -3313       0.00      0.00      0.00         1
       -1680       0.00      0.00      0.00         0
       -1400       0.00      0.00      0.00         0
       -1313       0.00      0.00      0.00         1
       -1206       0.00      0.00      0.00         0
       -1202       0.00      0.00      0.00         1
       -1053       0.00      0.00      0.00         0
        -970       0.00      0.00      0.00         1
        -967       0.00      0.00      0.00         0
        -966       0.00      0.00      0.00         1
        -938       0.00      0.00      0.00         0
        -932       0.00      0.00      0.00         0
        -839       0.00      0.00      0.00         0
        -762       0.00      0.00      0.00         1
        -715       0.00      0.00      0.00         0
        -710       0.00      0.00      0.00         0
        -701       0.00      0.00      0.00         1
        -673       0.00    

C:\Users\chand\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:98: UserWarning: The number of unique classes is greater than 50% of the number of samples.
  type_true = type_of_target(y_true, input_name="y_true")
C:\Users\chand\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:99: UserWarning: The number of unique classes is greater than 50% of the number of samples.
  type_pred = type_of_target(y_pred, input_name="y_pred")
C:\Users\chand\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\multiclass.py:79: UserWarning: The number of unique classes is greater than 50% of the number of samples.
  ys_types = set(type_of_target(x) for x in ys)
C:\Users\chand\AppData\Local\Packages\PythonS

In [85]:
from sklearn.metrics import precision_score , recall_score, f1_score
print(precision_score(y_test,pred, average= 'weighted'))
print(recall_score(y_test,pred, average= 'weighted'))
print(f1_score(y_test,pred, average= 'weighted' ))



0.008607764390896921
0.01
0.00924473493100944


C:\Users\chand\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:98: UserWarning: The number of unique classes is greater than 50% of the number of samples.
  type_true = type_of_target(y_true, input_name="y_true")
C:\Users\chand\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:99: UserWarning: The number of unique classes is greater than 50% of the number of samples.
  type_pred = type_of_target(y_pred, input_name="y_pred")
C:\Users\chand\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\multiclass.py:79: UserWarning: The number of unique classes is greater than 50% of the number of samples.
  ys_types = set(type_of_target(x) for x in ys)
C:\Users\chand\AppData\Local\Packages\PythonS

In [86]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,pred))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


C:\Users\chand\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:98: UserWarning: The number of unique classes is greater than 50% of the number of samples.
  type_true = type_of_target(y_true, input_name="y_true")
C:\Users\chand\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:99: UserWarning: The number of unique classes is greater than 50% of the number of samples.
  type_pred = type_of_target(y_pred, input_name="y_pred")
C:\Users\chand\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\multiclass.py:79: UserWarning: The number of unique classes is greater than 50% of the number of samples.
  ys_types = set(type_of_target(x) for x in ys)
C:\Users\chand\AppData\Local\Packages\PythonS

In [87]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier()
model.fit(x_train, y_train)

C:\Users\chand\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\neighbors\_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\chand\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\multiclass.py:213: UserWarning: The number of unique classes is greater than 50% of the number of samples.
  y_type = type_of_target(y, input_name="y")


KNeighborsClassifier()

In [88]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators = 100, random_state=42,min_samples_leaf=3)
model.fit(x_train, y_train)

C:\Users\chand\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:1363: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\chand\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\multiclass.py:213: UserWarning: The number of unique classes is greater than 50% of the number of samples.
  y_type = type_of_target(y, input_name="y")
C:\Users\chand\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\multiclass.py:213: UserWarning: The number of unique classes is greater than 50% of the number of samples.
  y_type = type_of_target(y, input_name="y")
C:\Users\chand\AppData\Loc

RandomForestClassifier(min_samples_leaf=3, random_state=42)

In [89]:
model.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 3,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': 42,
 'verbose': 0,
 'warm_start': False}

In [90]:
model.score(x_test, y_test)

C:\Users\chand\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:98: UserWarning: The number of unique classes is greater than 50% of the number of samples.
  type_true = type_of_target(y_true, input_name="y_true")


0.05333333333333334

In [91]:
model.score(x_train, y_train)

C:\Users\chand\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:98: UserWarning: The number of unique classes is greater than 50% of the number of samples.
  type_true = type_of_target(y_true, input_name="y_true")
C:\Users\chand\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:99: UserWarning: The number of unique classes is greater than 50% of the number of samples.
  type_pred = type_of_target(y_pred, input_name="y_pred")


0.9627777777777777

In [92]:
from sklearn.naive_bayes  import GaussianNB,MultinomialNB,BernoulliNB
model = GaussianNB()
model.fit(x_train, y_train)

C:\Users\chand\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\chand\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\multiclass.py:79: UserWarning: The number of unique classes is greater than 50% of the number of samples.
  ys_types = set(type_of_target(x) for x in ys)


GaussianNB()

In [93]:
model.score(x_test,y_test)

C:\Users\chand\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:98: UserWarning: The number of unique classes is greater than 50% of the number of samples.
  type_true = type_of_target(y_true, input_name="y_true")


0.03

In [94]:
model.score(x_train,y_train)

C:\Users\chand\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:98: UserWarning: The number of unique classes is greater than 50% of the number of samples.
  type_true = type_of_target(y_true, input_name="y_true")


0.48833333333333334